### ISSUE TITLE
Telegram join channel/group check doesn't work

### ISSUE THREAD

**Issue by nashyvan** [mujadmani/Easy-Telegram-Airdrop-Bot#4]
I don't know why but telegram join channel/group check doesn't work for me.
I think the problem is in [this](https://github.com/mujadmani/Easy-Telegram-Airdrop-Bot/blob/7538348e94947f5cef86fd5c6554e4dc06ac0170/bot.py#L280) function.
I also have an errors in heroku log
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/44340459/170842273-92e7f55d-a917-45d7-bcec-87f08eb3488b.png">

**Comment by lexciobotariu** [comment]
have you invited your bot to your group and channel?

**Comment by nashyvan** [comment]
Sorry but I don't even remember what the problem was
